### PR TITLE
improve readme

### PR DESCRIPTION
**Pull request by davibelini**
I though it'd be a cooler project with a better readme and an image to show what the program really does.
This is my first pull request and I like your golang content. :)

### CODE REVIEW

**Comment by filhodanuvem** [comment]
Hey @davibelini. Nice job! Thanks. 
I think you have added the binary in the commit, can you remove that?

**Comment by davibelini** [comment]
> Hey @davibelini. Nice job! Thanks. 
> I think you have added the binary in the commit, can you remove that please? 

Sure. Will do

**Comment by filhodanuvem** [comment]
Great job, thanks @davibelini 💪🏾

**Comment by davibelini** [comment]
Thanks @filhodanuvem !

**Pull request merged**
