### PR TITLE
Test language detector

### PR DESCRIPTION
**Pull request by esron**
Related to #4 

I'm opening this issue as WIP so we can have a discussion abou some patterns in tests.

I've created a folder with testdata so it can be ignored during build fase.

I'm thinking about splitting the issue so it is easier to evaluate.

If you have any suggestions or corrections to make I'm able to fix it.

### CODE REVIEW

**Comment by filhodanuvem** [comment]
The idea to have a `testdata` directory looks good @esron . I think for the tests would be good to have two different test cases, one for an invalid file and a second to a valid one. 
Just because when we run `go test -v` we see what tests are failing and it might be more meaningful. 
Additionally, I think that the tests are not running in the github actions, so it's better to active it as well. 
Thanks for the help.

**Comment by esron** [comment]
Hi @filhodanuvem is there a reason to keep the `downloader.go` file in the project's root folder? It seems to be causing some issues with the test script.

**Comment by filhodanuvem** [comment]
I did it to avoid circular dependencies. Mainly because I imagine a package for `github`, another for `gitlab`, `bitbucket`... and the interface must be outside of all of them. As we are far from there, you can follow any of the suggestions: 
- Move the interface to the `github`package
- Pass the packages that you want to test in the github actions. Eg.: `go test -v ./cmd ./github ./language`

**Comment by esron** [comment]
I've choose the last one.

For the invalid file you spoken of here:

> The idea to have a `testdata` directory looks good @esron . I think for the tests would be good to have two different test cases, one for an invalid file and a second to a valid one.
> Just because when we run `go test -v` we see what tests are failing and it might be more meaningful.
> Additionally, I think that the tests are not running in the github actions, so it's better to active it as well. Can you do that?
> Thanks for the help.

I've choose a simple text file.

It is ok?

**Comment by filhodanuvem** [comment]
That's look ok @esron . Thank you for the help!

**Pull request merged**
