### PR TITLE
Test files.go

### PR DESCRIPTION
**Pull request by esron**
Hi.

In this PR I'm trying to test the `GetFiles` function on `files.go`.

I've used the testify package to help me test the logs from logrus.

If it is overkill we can think of another ways of testing.

### CODE REVIEW

**Comment by filhodanuvem** [comment]
Sorry for the late @esron . I'm trying to find a time to improve the ticket #4. 
I think "Improve tests" is being too vague.

**Comment by esron** [comment]
What do you have in mind, @filhodanuvem ?

**Comment by filhodanuvem** [comment]
I would like to have in that issue a list of suggestions to improve the tests, then it would be easy to understand when it might be closed. 
Most of the system rely on file system or network (download from github/gitlab) but I would like to see more unit tests, I mean, run the tests without internet for example. To allow that the code might be refactored to make it possible to mock functions.

**Comment by esron** [comment]
That sounds good. But the event only goes until the end of the month. Of course I'm planning to still contribute to the project even when Hacktoberfest ends...

**Comment by filhodanuvem** [comment]
ah, got it. I have label it as hacktoberfest-accepted, let me know if it doesn't appear in your dashboard.

**Pull request closed without merging**
